services:
  database:
    environment:
      MARIADB_ROOT_PASSWORD: root
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ~/Sites/sumocoders/docker/mariadb:/var/lib/mysql