services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ~/Sites/sumocoders/docker/mysql57:/var/lib/mysql
