name: Test project skeleton

on:
  push:
    branches: ['*']
  workflow_dispatch:
    branches: ['*']

jobs:
  create-project:
    runs-on: "ubuntu-latest"

    steps:
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/fermium
      - name: Install volta
        uses: volta-cli/action@v3
      - name: Run composer create-project
        run: composer create-project --no-progress --stability=dev sumocoders/application-skeleton:dev-${GITHUB_REF##*/} test